name: Comment test coverage comparison
on:
  - pull_request

jobs:
  test-main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the main branch
        uses: actions/checkout@v5
        with:
          ref: main

      - name: Install dependencies
        run: npm install

      - name: Run tests with full coverage on main
        run: |
          npm run test:full-report > coverage-main.txt 2>&1

      - name: Upload main coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-main
          path: .

  test-current:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the current branch
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm install

      - name: Run tests with full coverage on current branch
        run: |
          npm run test:full-report > coverage-current.txt 2>&1

      - name: Upload current coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-current

  comment:
    needs:
      - test-main
      - test-current
    runs-on: ubuntu-latest
    steps:
      - name: Download main coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-main

      - name: Download current coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-current

      - name: Compare coverage reports
        id: compare
        run: |
          npm run compare-coverage-reports coverage-main/coverage-main.txt coverage-current/coverage-current.txt > coverage-comparison.txt 2>&1
          echo "COMPARISON<<EOF" >> $GITHUB_OUTPUT
          cat coverage-comparison.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Find existing coverage comparison comment
        id: find-comment
        uses: peter-evans/find-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "<!-- coverage-comparison -->"

      - name: Post or update coverage comparison comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Test Coverage Comparison

            ```
            ${{ steps.compare.outputs.COMPARISON }}
            ```

            <!-- coverage-comparison -->